version: "3"
services:
  # DB*****************************************
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=aphextwin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=parking
    restart: unless-stopped

  # angular*****************************************
  angular-docker-service:
    image: angular-docker-service1
    build:
      context: ../Frontend/ParkingApp
      dockerfile: ./Dockerfile.angular
    ports:
      - 4200:4200


  # app*****************************************
  springbootapp:
    image: springbootapp:latest
    network_mode: bridge
    container_name: springbootapp
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres


volumes:
  postgres-data:

