version: "3"

# Application properties
#SERVER_PORT:8080
#DEBUG_PORT:5005
#SPRING_PROFILES_ACTIVE:dev
#DEBUG:true
## -Dprop=... -Dparameter=...
##JAVA_OPTS=
#
## Host properties
#HOST_SERVER_PORT:8080
#HOST_DEBUG_PORT:5005

services:
    # DB*****************************************
    postgres:
        image: postgres:latest
        networks:
            - parking-network
        container_name: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        expose:
            - 5432
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=aphextwin
            - POSTGRES_USER=postgres
            - POSTGRES_DB=parking
            - DEBUG=true
        restart: unless-stopped

    # angular*****************************************
    angular-docker-service:
        image: angular-docker-service
        networks:
            - parking-network
        build:
            context: ../Frontend/ParkingApp
            dockerfile: ./Dockerfile.angular
        ports:
            - 4200:4200
        expose:
            - 4200
        environment:
            - DEBUG_PORT=5005
            - SPRING_PROFILES_ACTIVE=dev
            - DEBUG=true


    # app*****************************************
    springbootapp:
        image: springbootapp:latest
        networks:
            - parking-network

        container_name: springbootapp
        expose:
            - 8080
        ports:
            - 8080:8080
            - 5005:5005 # debug
        command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app/parking.jar
        restart: unless-stopped
        depends_on:
            - postgres
        environment:
            - DEBUG=true

networks:
    parking-network:

volumes:
    postgres-data:
