/*
 * Parking application Backend API
 * Parking IoT application project API reference for developers
 *
 * OpenAPI spec version: 0.2
 * Contact: parking_app_service@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.swaggen.parking.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * Social user model. 
 */
@Schema(description = "Social user model. ")
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-06T11:26:27.336+03:00[EET]")
public class SocialUser {
  @JsonProperty("email")
  private String email = null;

  @JsonProperty("firstname")
  private String firstname = null;

  @JsonProperty("lastname")
  private String lastname = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("socialIds")
  private Map<String, String> socialIds = null;

  @JsonProperty("username")
  private String username = null;

  public SocialUser email(String email) {
    this.email = email;
    return this;
  }

   /**
   * User email
   * @return email
  **/
  @Schema(description = "User email")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public SocialUser firstname(String firstname) {
    this.firstname = firstname;
    return this;
  }

   /**
   * User firstname
   * @return firstname
  **/
  @Schema(description = "User firstname")
  public String getFirstname() {
    return firstname;
  }

  public void setFirstname(String firstname) {
    this.firstname = firstname;
  }

  public SocialUser lastname(String lastname) {
    this.lastname = lastname;
    return this;
  }

   /**
   * User lastname
   * @return lastname
  **/
  @Schema(description = "User lastname")
  public String getLastname() {
    return lastname;
  }

  public void setLastname(String lastname) {
    this.lastname = lastname;
  }

  public SocialUser password(String password) {
    this.password = password;
    return this;
  }

   /**
   * User password
   * @return password
  **/
  @Schema(description = "User password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public SocialUser socialIds(Map<String, String> socialIds) {
    this.socialIds = socialIds;
    return this;
  }

  public SocialUser putSocialIdsItem(String key, String socialIdsItem) {
    if (this.socialIds == null) {
      this.socialIds = new HashMap<String, String>();
    }
    this.socialIds.put(key, socialIdsItem);
    return this;
  }

   /**
   * Map of user social id&#x27;s by social service providers
   * @return socialIds
  **/
  @Schema(description = "Map of user social id's by social service providers")
  public Map<String, String> getSocialIds() {
    return socialIds;
  }

  public void setSocialIds(Map<String, String> socialIds) {
    this.socialIds = socialIds;
  }

  public SocialUser username(String username) {
    this.username = username;
    return this;
  }

   /**
   * User username
   * @return username
  **/
  @Schema(required = true, description = "User username")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SocialUser socialUser = (SocialUser) o;
    return Objects.equals(this.email, socialUser.email) &&
        Objects.equals(this.firstname, socialUser.firstname) &&
        Objects.equals(this.lastname, socialUser.lastname) &&
        Objects.equals(this.password, socialUser.password) &&
        Objects.equals(this.socialIds, socialUser.socialIds) &&
        Objects.equals(this.username, socialUser.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, firstname, lastname, password, socialIds, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SocialUser {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    socialIds: ").append(toIndentedString(socialIds)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
