/*
 * Parking application Backend API
 * Parking IoT application project API reference for developers
 *
 * OpenAPI spec version: 0.2
 * Contact: parking_app_service@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.swaggen.parking.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import javax.annotation.processing.Generated;
import java.util.Objects;


/**
 * Statistics entry model
 */
@Schema(description = "Statistics entry model")
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-06T11:26:27.336+03:00[EET]")
public class StatisticsRecord {
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("lotNumber")
    private Integer lotNumber = null;

    @JsonProperty("status")
    private StatusEnum status = null;

    @JsonProperty("updatedAt")
    private OffsetDateTime updatedAt = null;

    public StatisticsRecord id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Statistics record unique id
     *
     * @return id
     **/
    @Schema(description = "Statistics record unique id")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public StatisticsRecord lotNumber(Integer lotNumber) {
        this.lotNumber = lotNumber;
        return this;
    }

    /**
     * Statistics record lot number
     *
     * @return lotNumber
     **/
    @Schema(description = "Statistics record lot number")
    public Integer getLotNumber() {
        return lotNumber;
    }

    public void setLotNumber(Integer lotNumber) {
        this.lotNumber = lotNumber;
    }

    public StatisticsRecord status(StatusEnum status) {
        this.status = status;
        return this;
    }

    /**
     * Statistics record lot status
     *
     * @return status
     **/
    @Schema(description = "Statistics record lot status")
    public StatusEnum getStatus() {
        return status;
    }

    public void setStatus(StatusEnum status) {
        this.status = status;
    }

    public StatisticsRecord updatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Statistics record date
     *
     * @return updatedAt
     **/
    @Schema(description = "Statistics record date")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StatisticsRecord statisticsRecord = (StatisticsRecord) o;
        return Objects.equals(this.id, statisticsRecord.id) &&
                Objects.equals(this.lotNumber, statisticsRecord.lotNumber) &&
                Objects.equals(this.status, statisticsRecord.status) &&
                Objects.equals(this.updatedAt, statisticsRecord.updatedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, lotNumber, status, updatedAt);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class StatisticsRecord {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    lotNumber: ").append(toIndentedString(lotNumber)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Statistics record lot status
     */
    public enum StatusEnum {
        FREE("FREE"),
        OCCUPIED("OCCUPIED"),
        RESERVED("RESERVED"),
        UNKNOWN("UNKNOWN");

        private String value;

        StatusEnum(String value) {
            this.value = value;
        }

        @JsonCreator
        public static StatusEnum fromValue(String text) {
            for (StatusEnum b : StatusEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

    }

}
