/*
 * Parking application Backend API
 * Parking IoT application project API reference for developers
 *
 * OpenAPI spec version: 0.2
 * Contact: parking_app_service@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.swaggen.parking.client.api;

import com.swaggen.parking.client.model.StatisticsRecord;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatisticsControllerApi
 */
@Ignore
public class StatisticsControllerApiTest {

    private final StatisticsControllerApi api = new StatisticsControllerApi();

    /**
     * Get all statistics records from database
     *
     * Returns all statistics records from storage
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllStatisticsUsingGETTest() {
        List<StatisticsRecord> response = api.getAllStatisticsUsingGET();

        // TODO: test validations
    }
    /**
     * Get all statistics records by parking lot number from database
     *
     * Returns all statistics records by parking lot number from storage
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStatisticsByLotNumberUsingGETTest() {
        String lotNumber = null;
        List<StatisticsRecord> response = api.getStatisticsByLotNumberUsingGET(lotNumber);

        // TODO: test validations
    }
}
