spring:

    # ===============================
    # DATABASE CONNECTION
    # ===============================

    datasource:
        # PostgresDB config
        url: jdbc:postgresql://localhost:5432/parking
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver

        # H2 In memory database config
        # url: jdbc:h2:mem:testdb
        # driverClassName: org.h2.Driver
        # username: h2
        # password: sa

        # H2 persistent data store
        ## temporary data storage
        # url: jdbc:h2:mem:testdb
        #
        ## temporary data storage
        #url: jdbc:h2:file:/data/sample
        #url: jdbc:h2:file:C:/data/sample (Windows only)

        # Setting for filling initial data
        # fallback database storage
        # set this to always for load initial data from data-postgresql.sql file
        initialization-mode: never
        platform: postgresql

    # ===============================
    # JPA / HIBERNATE
    # ===============================

    data:
        jpa:
            repositories:
                enabled: true

        ldap:
            repositories:
                enabled: true
    jpa:
        show-sql: true
        # database-platform: org.hibernate.dialect.H2Dialect

        ### Hibernate Properties
        ## The SQL dialect makes Hibernate generate better SQL for the chosen database
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

        ### Hibernate ddl auto (create, create-drop, validate, update)
        # set this to create-drop for first launch for create and fill initial database structure
        # after first application launch change parameter below to validate
        hibernate:
            ddl-auto: update

            ### Enable columns naming from entities annotation
            # standard Hibernate naming strategy
            naming_strategy: org.hibernate.cfg.EJB3NamingStrategy

    # Enabling H2 Console
    h2:
        console:
            enabled: true
            # Custom H2 Console URL
            path: /h2

    # ===============================
    # Schedule / Tasks
    # ===============================

    # Enable scheduling tasks
    # Need to be enabled for executing statistics clearing
    enable:
        scheduling: true

    # ===============================
    # SECURITY
    # ===============================

    ####### Security LDAP #######
    # Embedded LDAP server
    ldap:
        embedded:
            ldif: classpath:ldap-server.ldif
            base-dn: dc=isd,dc=com
            port: 8389
            # Whether to enable LDAP schema validation.
            # false param OFF's com.unboundid.ldap.sdk schema validation
            validation:
                enabled: false
                # Path to the custom schema.
                schema: classpath:custom-schema.ldif

            credential:
                username: uid=admin
                password: pass1
        base: ou=people

    #Spring Boot Console
    main:
        banner-mode:
            off
    output:
        ansi:
            enabled: ALWAYS

# External LDAP server
ldap:
    base:
        dn: dc=isd,dc=com
    partitionSuffix: dc=isd,dc=com
    partition: example
    port: 8389
    url: ldap://localhost:8389
    user:
        dn:
            pattern: uid={0},ou=people
    userSearchFilter: uid={0}
    groupSearchBase: ou=groups
    groupSearchFilter: uniqueMember={0}
    passwordAttribute: userPassword
    username: myuserid
    password: secretthingy

### Setting for background task
scheduler:
    delete-stats:
        cron: "0 0 1 * * *"

# Logging pattern
logging:
    pattern:
        console:
            regexp: '%date  %highlight(%-5level) [%12.12thread] %cyan(%-40.40logger{40}): %msg %n'

    # Debug
    spring.devtools.add-properties=true

  # Additional WEB interaction level logging
  # logging.level.web=DEBUG

    spring.pid.fail-on-write-error=true
    spring.pid.file=/server-path-with-folder-as-app-name-for-ID/appName/appName.pid


### Frontend application URL
front:
    url: http://localhost:4200

# ===============================
# SERVER
# ===============================

### Server port (change if already used)
server:
    port: 8080
#ssl:enabled=true
#ssl:key-store=classpath:main.jks
#ssl:key-password=secret

# Remote shutdown
# Enable shutdown endpoint
management:
    endpoints:
        web:
            exposure:
                include: *
    endpoint:
        shutdown:
            enabled: true


####### Parking lots ########
# Parking lots number
parking:
    lots:
        number=10
